[install]
# Configurações de instalação
cache = true
exact = false
production = false

# [install.scopes]
# Configurações para escopo de pacotes removidas
# "@types" = "latest" # Esta configuração estava causando erro de registry

[build]
# Configurações de build
target = "bun"
outdir = "dist"
minify = true
sourcemap = false

[test]
# Configurações de teste
timeout = 5000
coverage = false

[lockfile]
# Configurações do lockfile
print = "yarn" 