name: Configurar Proteções de Branch


on:
  push:
    branches: [ main, develop ]

permissions:
  contents: write
  actions: write
  checks: write
  pull-requests: write

jobs:
  setup-branch-protection:
    name: Verificar Proteções
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Verificar se proteções podem ser configuradas
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: branches } = await github.rest.repos.listBranches({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const mainBranch = branches.find(b => b.name === 'main');
              if (mainBranch) {
                console.log('✅ Branch main encontrado');
                console.log('ℹ️  Para configurar proteções de branch, use um token com permissão de administração');
                console.log('ℹ️  Ou configure manualmente nas configurações do repositório');
              }
            } catch (error) {
              console.log('⚠️  Não foi possível configurar proteções automaticamente');
              console.log('ℹ️  Configure manualmente em: Settings > Branches > Add rule');
            } 