name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUN_VERSION: '1.2.13'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ env.BUN_VERSION }}

    - name: Cache dependências
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
        
    - name: Install dependencies
      run: bun install
      
    - name: Check TypeScript types
      run: bun run tsc --noEmit
      
    - name: Run tests
      run: bun test
      
    - name: Run tests with coverage
      run: bun run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Run integration tests
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "ci@example.com"
        bun test tests/integration.test.ts
        
    - name: Run Smart Split tests
      run: bun test tests/smart-split.test.ts
        
    - name: Build project
      run: bun run build
      
    - name: Verify build
      run: |
        if [ -f "dist/commit-wizard.js" ]; then
          echo "✅ Build gerado com sucesso"
          ls -la dist/
          chmod +x dist/commit-wizard.js
          timeout 10s bun run dist/commit-wizard.js --help || true
        else
          echo "❌ Build falhou"
          exit 1
        fi

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ env.BUN_VERSION }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Build project
      run: bun run build
      
    - name: Check if version changed
      id: check
      uses: EndBug/version-check@v2
      with:
        diff-search: true
        
    - name: Publish to NPM
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      if: steps.check.outputs.changed == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.check.outputs.version }}
        release_name: Release v${{ steps.check.outputs.version }}
        draft: false
        prerelease: false
        body: |
          🚀 Nova versão do Commit Wizard: v${{ steps.check.outputs.version }}
          
          ## Instalação
          ```bash
          npm install -g commit-wizard
          ```
          
          ## Como usar
          ```bash
          commit-wizard
          ```
          
          Para mais informações, consulte o [README](https://github.com/gilbert-oliveira/commit-wizard#readme).
